export async function seed(knex) {
  // ── Idempotency guard — skip if already seeded ───────────────────────────────
  const { count } = await knex('products').count('id as count').first();
  if (parseInt(count) > 0) {
    console.log(`Seed skipped — ${count} products already exist.`);
    return;
  }

  // ── Clear existing data safely ───────────────────────────────────────────────
  await knex('products').del();
  if (await knex.schema.hasColumn('categories', 'parent_id')) {
    await knex.raw('UPDATE categories SET parent_id = NULL');
  }
  await knex('categories').del();

  // ── Helper — cast JS value to jsonb ─────────────────────────────────────────
  const j = (val) => knex.raw('?::jsonb', [JSON.stringify(val)]);

  // ── Insert PARENT categories ─────────────────────────────────────────────────
  const [men] = await knex('categories')
    .insert({ name: 'Men', slug: 'men', description: "Men's fashion collection." })
    .returning('*');

  const [women] = await knex('categories')
    .insert({ name: 'Women', slug: 'women', description: "Women's fashion collection." })
    .returning('*');

  const [sport] = await knex('categories')
    .insert({ name: 'Sportswear', slug: 'sportswear', description: 'Performance sportswear and activewear.' })
    .returning('*');

  const [acc] = await knex('categories')
    .insert({ name: 'Accessories', slug: 'accessories', description: 'Accessories — caps, watches, lifestyle pieces.' })
    .returning('*');

  // ── Insert SUB-categories ────────────────────────────────────────────────────
  const subs = await knex('categories')
    .insert([
      { name: "Men's T-shirts",    slug: 'men-tshirts',      description: "Men's T-shirts and tees.",                     parent_id: men.id   },
      { name: "Men's Shirts",      slug: 'men-shirts',       description: "Men's shirts and button-downs.",               parent_id: men.id   },
      { name: "Men's Pants",       slug: 'men-pants',        description: "Men's pants and trousers.",                    parent_id: men.id   },
      { name: "Women's T-shirts",  slug: 'women-tshirts',   description: "Women's T-shirts and tees.",                   parent_id: women.id },
      { name: "Women's Shirts",    slug: 'women-shirts',    description: "Women's shirts and blouses.",                  parent_id: women.id },
      { name: "Women's Pants",     slug: 'women-pants',     description: "Women's pants and trousers.",                  parent_id: women.id },
      { name: 'Sportswear Men',    slug: 'sportswear-men',  description: "Men's performance sportswear and activewear.", parent_id: sport.id },
      { name: 'Sportswear Women',  slug: 'sportswear-women', description: "Women's performance sportswear and activewear.", parent_id: sport.id },
    ])
    .returning('*');

  const cat = Object.fromEntries(subs.map(c => [c.slug, c.id]));
  cat['accessories'] = acc.id;

  // ────────────────────────────────────────────────────────────────────────────
  // PRODUCTS
  // ────────────────────────────────────────────────────────────────────────────

  // ── Men's T-shirts ───────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['men-tshirts'],
      name:           'TWENTYSEVEN SS25 Black Tee',
      slug:           'twentyseven-ss25-black-tee',
      description:    'Oversized premium cotton tee from the TWENTYSEVEN SS25 collection. Features embroidered logo and season branding on the chest. Heavyweight drop-shoulder cut for the perfect oversized streetwear fit.',
      price:          799,
      stock_qty:      50,
      is_new_arrival: true,
      image_url:      '/uploads/product_upload_12.jpg',
      image_gallery:  j(['/uploads/product_upload_12.jpg']),
      colors:         j(['Black']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Black: '/uploads/product_upload_12.jpg' }),
    },
    {
      category_id:    cat['men-tshirts'],
      name:           'TWENTYSEVEN 27 Rose Tee',
      slug:           'twentyseven-27-rose-tee',
      description:    'Boxy oversized tee in a soft rose pink colorway. Features tonal 27 logo embroidery on chest. Made from 100% heavyweight cotton for a premium feel and effortless all-day comfort.',
      price:          749,
      stock_qty:      45,
      is_new_arrival: true,
      image_url:      '/uploads/product_upload_13.jpg',
      image_gallery:  j(['/uploads/product_upload_13.jpg']),
      colors:         j(['Pink']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Pink: '/uploads/product_upload_13.jpg' }),
    },
    {
      category_id:    cat['men-tshirts'],
      name:           'Spirits of a Dreamer Tee',
      slug:           'spirits-of-a-dreamer-tee',
      description:    'Statement oversized tee featuring the iconic "Spirits of a Dreamer" script print across the chest. 100% premium heavyweight cotton in a relaxed drop-shoulder cut. A signature piece from the TWENTYSEVEN collection.',
      price:          849,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/product_upload_14.jpg',
      image_gallery:  j(['/uploads/product_upload_14.jpg']),
      colors:         j(['White']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ White: '/uploads/product_upload_14.jpg' }),
    },
    {
      category_id:    cat['men-tshirts'],
      name:           'TWENTYSEVEN Ribbed Knit Polo',
      slug:           'twentyseven-ribbed-knit-polo',
      description:    'Premium ribbed knit polo with an open-collar design. Fine cotton-blend knit with vertical texture detail. A refined, elevated take on the classic polo engineered for smart casual styling.',
      price:          999,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/product_upload_15.jpg',
      image_gallery:  j(['/uploads/product_upload_15.jpg']),
      colors:         j(['White']),
      sizes:          j(['S', 'M', 'L', 'XL']),
      color_images:   j({ White: '/uploads/product_upload_15.jpg' }),
    },
    {
      category_id:    cat['men-tshirts'],
      name:           'TWENTYSEVEN 27 Graphic Tee',
      slug:           'twentyseven-27-graphic-tee',
      description:    'Oversized graphic tee featuring the bold distressed "27" logo print on the chest. Heavyweight drop-shoulder cut in 100% premium cotton. An everyday essential that defines the TWENTYSEVEN streetwear aesthetic.',
      price:          749,
      stock_qty:      50,
      is_new_arrival: true,
      image_url:      '/uploads/product_upload_16.jpg',
      image_gallery:  j(['/uploads/product_upload_16.jpg']),
      colors:         j(['White']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ White: '/uploads/product_upload_16.jpg' }),
    },
    {
      category_id:    cat['men-tshirts'],
      name:           'Salty 023 Knit Polo',
      slug:           'salty-023-knit-polo',
      description:    'Premium short-sleeve knit polo in sage grey with a bold black centre-stripe and "Salty" script logo. Features "023" number embroidery on both sleeves and ribbed black cuffs and hem. A statement-making piece that fuses sportswear heritage with streetwear attitude.',
      price:          1199,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/product_upload_18.jpg',
      image_gallery:  j(['/uploads/product_upload_18.jpg']),
      colors:         j(['Gray']),
      sizes:          j(['S', 'M', 'L', 'XL']),
      color_images:   j({ Gray: '/uploads/product_upload_18.jpg' }),
    },
    {
      category_id:    cat['men-tshirts'],
      name:           'TWENTYSEVEN Established Green Tee',
      slug:           'twentyseven-established-green-tee',
      description:    'Oversized heavyweight tee in deep forest green. Features a tonal script logo on the chest with "TwentySeven — Every Summer Clique, Established, Cairo, Egypt" branding. 100% premium cotton in a relaxed drop-shoulder fit. A true Cairo streetwear staple.',
      price:          799,
      stock_qty:      45,
      is_new_arrival: true,
      image_url:      '/uploads/product_upload_19.jpg',
      image_gallery:  j(['/uploads/product_upload_19.jpg']),
      colors:         j(['Green']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Green: '/uploads/product_upload_19.jpg' }),
    },
    {
      category_id:    cat['men-tshirts'],
      name:           'Unknown Desire Acid Wash Tee',
      slug:           'unknown-desire-acid-wash-tee',
      description:    'Heavyweight oversized tee in a sand acid-wash finish. Features the "Unknown Desire" distressed graphic print with a skull motif across the chest. Garment-dyed for a unique vintage texture — no two pieces are exactly alike. 100% premium cotton, boxy streetwear cut.',
      price:          849,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/product_upload_20.jpg',
      image_gallery:  j(['/uploads/product_upload_20.jpg']),
      colors:         j(['Beige']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Beige: '/uploads/product_upload_20.jpg' }),
    },
  ]);

  // ── Men's Shirts ─────────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['men-shirts'],
      name:           'Teal Diamond Lace Short Sleeve Shirt',
      slug:           'teal-diamond-lace-short-sleeve-shirt',
      description:    'Statement short-sleeve shirt in rich teal blue crafted from a semi-sheer geometric diamond lace fabric. Features a classic camp collar, button-through front, and relaxed fit. Bold yet refined — a standout summer piece that effortlessly elevates any casual outfit.',
      price:          1099,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/menshirt_upload_00.jpg',
      image_gallery:  j(['/uploads/menshirt_upload_00.jpg']),
      colors:         j(['Blue']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Blue: '/uploads/menshirt_upload_00.jpg' }),
    },
    {
      category_id:    cat['men-shirts'],
      name:           'Acid Wash Plaid Flannel Overshirt',
      slug:           'acid-wash-plaid-flannel-overshirt',
      description:    'Oversized long-sleeve button-down in a blue and brown plaid flannel with a distinctive acid-wash treatment for a one-of-a-kind vintage finish. Relaxed drop-shoulder fit with a classic point collar. Worn open over a tee or buttoned up — a grunge-inspired wardrobe staple.',
      price:          999,
      stock_qty:      25,
      is_new_arrival: true,
      image_url:      '/uploads/menshirt_upload_01.jpg',
      image_gallery:  j(['/uploads/menshirt_upload_01.jpg']),
      colors:         j(['Blue']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Blue: '/uploads/menshirt_upload_01.jpg' }),
    },
    {
      category_id:    cat['men-shirts'],
      name:           'Denjoe Studio Striped Oversized Shirt',
      slug:           'denjoe-studio-striped-oversized-shirt',
      description:    'Oversized short-sleeve button-down in a classic mocha and white pinstripe poplin. Features a chest patch pocket with "Denjoe Studio." script embroidery, a classic point collar, and a boxy relaxed cut. A clean, elevated everyday shirt with a signature streetwear touch.',
      price:          949,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/menshirt_upload_02.jpg',
      image_gallery:  j(['/uploads/menshirt_upload_02.jpg']),
      colors:         j(['Beige']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Beige: '/uploads/menshirt_upload_02.jpg' }),
    },
  ]);

  // ── Men's Pants ──────────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['men-pants'],
      name:           'Beige Wide-Leg Linen Trousers',
      slug:           'beige-wide-leg-linen-trousers',
      description:    'Ultra-wide-leg trousers in lightweight sand beige linen. Features an elasticated drawstring waist for all-day comfort and a dramatic floor-grazing silhouette. Breathable and relaxed — a summer essential that moves with you.',
      price:          899,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/mpants_upload_00.jpg',
      image_gallery:  j(['/uploads/mpants_upload_00.jpg']),
      colors:         j(['Beige']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Beige: '/uploads/mpants_upload_00.jpg' }),
    },
    {
      category_id:    cat['men-pants'],
      name:           'Black Wide-Leg Corduroy Trousers',
      slug:           'black-wide-leg-corduroy-trousers',
      description:    'Relaxed wide-leg trousers in rich black corduroy with a thick-wale texture. Features a drawstring elasticated waist and a clean straight silhouette. A versatile everyday staple with a tactile premium finish.',
      price:          999,
      stock_qty:      28,
      is_new_arrival: true,
      image_url:      '/uploads/mpants_upload_01.jpg',
      image_gallery:  j(['/uploads/mpants_upload_01.jpg']),
      colors:         j(['Black']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Black: '/uploads/mpants_upload_01.jpg' }),
    },
    {
      category_id:    cat['men-pants'],
      name:           'Olive Tactical Cargo Pants',
      slug:           'olive-tactical-cargo-pants',
      description:    'Straight-fit cargo pants in dark olive heavy-cotton twill. Features six utility pockets including oversized side cargo pockets with button flaps, a branded label tab, and a drawstring waist. Built for the streets — functional, durable, and unapologetically bold.',
      price:          1199,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/mpants_upload_02.jpg',
      image_gallery:  j(['/uploads/mpants_upload_02.jpg']),
      colors:         j(['Olive']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Olive: '/uploads/mpants_upload_02.jpg' }),
    },
    {
      category_id:    cat['men-pants'],
      name:           'Ice Wash Baggy Jeans',
      slug:           'ice-wash-baggy-jeans',
      description:    'Relaxed baggy-fit jeans in a light ice-blue wash denim. Classic 5-pocket construction with a high-rise waist, roomy thigh, and straight wide leg. The ultimate streetwear denim staple — pair with anything for an effortlessly cool look.',
      price:          1099,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/mpants_upload_03.jpg',
      image_gallery:  j(['/uploads/mpants_upload_03.jpg']),
      colors:         j(['Light Blue']),
      sizes:          j(['28', '30', '32', '34', '36']),
      color_images:   j({ 'Light Blue': '/uploads/mpants_upload_03.jpg' }),
    },
    {
      category_id:    cat['men-pants'],
      name:           'White Linen Drawstring Trousers',
      slug:           'white-linen-drawstring-trousers',
      description:    'Clean straight-cut trousers in off-white crinkle linen. Features a front drawstring waist for an adjustable relaxed fit. Lightweight, breathable, and minimal — the perfect resort or summer-in-the-city trouser.',
      price:          849,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/mpants_upload_04.jpg',
      image_gallery:  j(['/uploads/mpants_upload_04.jpg']),
      colors:         j(['White']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ White: '/uploads/mpants_upload_04.jpg' }),
    },
  ]);

  // ── Women's T-shirts ─────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['women-tshirts'],
      name:           "TWENTYSEVEN 27 Women's Oversized Tee",
      slug:           'twentyseven-27-womens-oversized-tee',
      description:    'Relaxed oversized tee in off-white featuring a tonal gothic "27" logo embroidered on the chest. 100% heavyweight premium cotton in a drop-shoulder boxy cut. The perfect effortless everyday piece from the TWENTYSEVEN women\'s collection.',
      price:          749,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/women_upload_00.jpg',
      image_gallery:  j(['/uploads/women_upload_00.jpg']),
      colors:         j(['White']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ White: '/uploads/women_upload_00.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           "TWENTYSEVEN Established Women's Pink Tee",
      slug:           'twentyseven-established-womens-pink-tee',
      description:    'Oversized boxy tee in soft blush pink featuring a vertical tonal column print with the TWENTYSEVEN "All Moments / Fashion Is… / Straight From Cairo / Because / EST.2023" branding. 100% premium cotton. A statement piece celebrating Cairo streetwear culture.',
      price:          799,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/women_upload_01.jpg',
      image_gallery:  j(['/uploads/women_upload_01.jpg']),
      colors:         j(['Pink']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Pink: '/uploads/women_upload_01.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           "VEGA Women's Graphic Tee",
      slug:           'vega-womens-graphic-tee',
      description:    'Oversized heavyweight tee in army olive green featuring a bold tonal "VEGA" logo print across the chest. 100% premium cotton in a relaxed drop-shoulder fit. A clean, impactful graphic tee that brings a streetwear-meets-utilitarian energy to any look.',
      price:          749,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/women_upload_02.jpg',
      image_gallery:  j(['/uploads/women_upload_02.jpg']),
      colors:         j(['Olive']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Olive: '/uploads/women_upload_02.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           'Cowboy Baby Tee',
      slug:           'cowboy-baby-tee',
      description:    'Fitted cropped baby tee in crisp white with a pink outline cowboy hat and boots graphic print on the chest. Slim-fit ribbed cotton for a clean, feminine silhouette. A playful statement piece with a Western-inspired edge.',
      price:          649,
      stock_qty:      45,
      is_new_arrival: true,
      image_url:      '/uploads/women_upload_03.jpg',
      image_gallery:  j(['/uploads/women_upload_03.jpg']),
      colors:         j(['White']),
      sizes:          j(['XS', 'S', 'M', 'L']),
      color_images:   j({ White: '/uploads/women_upload_03.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           'Cin Cin Baby Tee',
      slug:           'cin-cin-baby-tee',
      description:    'Fitted cropped baby tee in candy pink featuring a hand-drawn red "Cin Cin / Dapperza" cocktail glass graphic on the chest. Slim-fit cotton with a rounded neckline. The ultimate summer statement piece — raise a glass to good style.',
      price:          649,
      stock_qty:      45,
      is_new_arrival: true,
      image_url:      '/uploads/women_upload_04.jpg',
      image_gallery:  j(['/uploads/women_upload_04.jpg']),
      colors:         j(['Pink']),
      sizes:          j(['XS', 'S', 'M', 'L']),
      color_images:   j({ Pink: '/uploads/women_upload_04.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           'Salty Studios Chili Baby Tee',
      slug:           'salty-studios-chili-baby-tee',
      description:    'Fitted baby tee in slate grey featuring the "SaltyStudios." logo and a bold red chili peppers graphic print on the chest. Slim-fit cotton with a round neck and cap sleeves. A spicy statement piece with serious streetwear attitude.',
      price:          649,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/women2_upload_00.jpg',
      image_gallery:  j(['/uploads/women2_upload_00.jpg']),
      colors:         j(['Gray']),
      sizes:          j(['XS', 'S', 'M', 'L']),
      color_images:   j({ Gray: '/uploads/women2_upload_00.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           'Heart Ribbed Tank Top',
      slug:           'heart-ribbed-tank-top',
      description:    'Clean ribbed tank top in crisp white with a small red heart embroidered at the centre chest. Features a scoop neckline and a flattering fitted silhouette. An everyday essential that effortlessly blends minimal and romantic.',
      price:          549,
      stock_qty:      50,
      is_new_arrival: true,
      image_url:      '/uploads/women2_upload_01.jpg',
      image_gallery:  j(['/uploads/women2_upload_01.jpg']),
      colors:         j(['White']),
      sizes:          j(['XS', 'S', 'M', 'L']),
      color_images:   j({ White: '/uploads/women2_upload_01.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           'Black Bandeau Tube Top',
      slug:           'black-bandeau-tube-top',
      description:    'Minimalist strapless bandeau tube top in matte black stretch-cotton. A wardrobe staple that pairs with everything — high-waist jeans, wide-leg trousers, or layered under an oversized shirt. Fitted, secure, and endlessly versatile.',
      price:          449,
      stock_qty:      55,
      is_new_arrival: true,
      image_url:      '/uploads/women2_upload_02.jpg',
      image_gallery:  j(['/uploads/women2_upload_02.jpg']),
      colors:         j(['Black']),
      sizes:          j(['XS', 'S', 'M', 'L']),
      color_images:   j({ Black: '/uploads/women2_upload_02.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           'Asymmetric Ribbed Long Sleeve Top',
      slug:           'asymmetric-ribbed-long-sleeve-top',
      description:    'Sculptural long-sleeve top in icy silver-grey fine rib. Features a boat neckline, full-length sleeves, and a dramatic pointed asymmetric hem for an architectural silhouette. Stretch ribbed fabric for a second-skin fit. A minimalist statement piece.',
      price:          699,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/women2_upload_03.jpg',
      image_gallery:  j(['/uploads/women2_upload_03.jpg']),
      colors:         j(['Gray']),
      sizes:          j(['XS', 'S', 'M', 'L']),
      color_images:   j({ Gray: '/uploads/women2_upload_03.jpg' }),
    },
    {
      category_id:    cat['women-tshirts'],
      name:           'One Shoulder Ribbed Crop Top',
      slug:           'one-shoulder-ribbed-crop-top',
      description:    'Sleek one-shoulder crop top in black ribbed stretch-cotton. Features a raw-edge single strap, asymmetric neckline, and a cropped hem with a subtle diagonal cut. Minimal, bold, and effortlessly cool.',
      price:          599,
      stock_qty:      45,
      is_new_arrival: true,
      image_url:      '/uploads/women2_upload_04.jpg',
      image_gallery:  j(['/uploads/women2_upload_04.jpg']),
      colors:         j(['Black']),
      sizes:          j(['XS', 'S', 'M', 'L']),
      color_images:   j({ Black: '/uploads/women2_upload_04.jpg' }),
    },
  ]);

  // ── Women's Shirts ───────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['women-shirts'],
      name:           'White Wide Sleeve Linen Shirt',
      slug:           'white-wide-sleeve-linen-shirt',
      description:    'Oversized V-neck shirt in sheer white linen-cotton with dramatic wide 3/4 sleeves and a relaxed boxy silhouette. Features a classic point collar, button-through front, and chest patch pocket. Light, breathable, and effortlessly elegant — a wardrobe staple for any season.',
      price:          899,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/wshirt_upload_00.jpg',
      image_gallery:  j(['/uploads/wshirt_upload_00.jpg']),
      colors:         j(['White']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ White: '/uploads/wshirt_upload_00.jpg' }),
    },
    {
      category_id:    cat['women-shirts'],
      name:           'Cream Kimono Tie Shirt',
      slug:           'cream-kimono-tie-shirt',
      description:    'Relaxed cropped shirt in natural cream crinkle-cotton with a kimono-inspired open-front silhouette. Features a single tie closure at the chest, wide bell sleeves, and a collarless V-neckline. Worn open or tied — an effortless resort-ready layering piece.',
      price:          849,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/wshirt_upload_01.jpg',
      image_gallery:  j(['/uploads/wshirt_upload_01.jpg']),
      colors:         j(['Cream']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Cream: '/uploads/wshirt_upload_01.jpg' }),
    },
    {
      category_id:    cat['women-shirts'],
      name:           'Black Zip-Up Overshirt',
      slug:           'black-zip-up-overshirt',
      description:    'Structured oversized overshirt in matte black heavy-cotton with a full zip-front closure, classic point collar, and wide drop-shoulder sleeves. Features side zip pockets for a utilitarian edge. Bold and minimal — the ultimate layering statement piece.',
      price:          1199,
      stock_qty:      25,
      is_new_arrival: true,
      image_url:      '/uploads/wshirt_upload_02.jpg',
      image_gallery:  j(['/uploads/wshirt_upload_02.jpg']),
      colors:         j(['Black']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Black: '/uploads/wshirt_upload_02.jpg' }),
    },
  ]);

  // ── Women's Pants ────────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['women-pants'],
      name:           'Butter Yellow Wide-Leg Linen Pants',
      slug:           'butter-yellow-wide-leg-linen-pants',
      description:    'Breezy wide-leg trousers in soft butter yellow lightweight linen. Features an elasticated drawstring waist, side seam pockets, and a relaxed floor-grazing silhouette. The ultimate summer statement — effortless, colourful, and cool.',
      price:          849,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/wpants_upload_00.jpg',
      image_gallery:  j(['/uploads/wpants_upload_00.jpg']),
      colors:         j(['Cream']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Cream: '/uploads/wpants_upload_00.jpg' }),
    },
    {
      category_id:    cat['women-pants'],
      name:           'Dark Indigo Wide-Leg Jeans',
      slug:           'dark-indigo-wide-leg-jeans',
      description:    'Raw-denim wide-leg jeans in deep indigo blue with contrast gold stitching. Features an asymmetric waistband with a low-rise cut, an extreme wide leg, and a floor-sweeping length. A bold, fashion-forward denim silhouette for those who dare to stand out.',
      price:          1299,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/wpants_upload_01.jpg',
      image_gallery:  j(['/uploads/wpants_upload_01.jpg']),
      colors:         j(['Dark Blue']),
      sizes:          j(['26', '28', '30', '32', '34']),
      color_images:   j({ 'Dark Blue': '/uploads/wpants_upload_01.jpg' }),
    },
    {
      category_id:    cat['women-pants'],
      name:           'Blue Striped Wide-Leg Linen Trousers',
      slug:           'blue-striped-wide-leg-linen-trousers',
      description:    'Flowing wide-leg trousers in a blue and white vertical stripe linen. Features a wrap-style tie waistband that knots at the side for an adjustable, effortlessly chic finish. Lightweight and breathable — a resort-ready essential with a relaxed Mediterranean spirit.',
      price:          949,
      stock_qty:      25,
      is_new_arrival: true,
      image_url:      '/uploads/wpants_upload_02.jpg',
      image_gallery:  j(['/uploads/wpants_upload_02.jpg']),
      colors:         j(['Blue']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Blue: '/uploads/wpants_upload_02.jpg' }),
    },
    {
      category_id:    cat['women-pants'],
      name:           'Mid-Wash Wide-Leg Rolled Cuff Jeans',
      slug:           'mid-wash-wide-leg-rolled-cuff-jeans',
      description:    'Relaxed wide-leg jeans in a mid-blue wash denim with a high-rise waist and a statement rolled cuff at the hem. 5-pocket classic construction with a roomy, curved silhouette. Timeless streetwear denim done in the most effortlessly cool way.',
      price:          1199,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/wpants_upload_03.jpg',
      image_gallery:  j(['/uploads/wpants_upload_03.jpg']),
      colors:         j(['Blue']),
      sizes:          j(['26', '28', '30', '32', '34']),
      color_images:   j({ Blue: '/uploads/wpants_upload_03.jpg' }),
    },
    {
      category_id:    cat['women-pants'],
      name:           'Pink Linen Drawstring Trousers',
      slug:           'pink-linen-drawstring-trousers',
      description:    'Lightweight wide-leg trousers in soft lilac pink crinkle-linen. Features an elasticated waist with a matching pink ribbon drawstring, side slip pockets, and a relaxed straight-leg cut. Sweet, minimal, and infinitely wearable.',
      price:          799,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/wpants_upload_04.jpg',
      image_gallery:  j(['/uploads/wpants_upload_04.jpg']),
      colors:         j(['Pink']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Pink: '/uploads/wpants_upload_04.jpg' }),
    },
  ]);

  // ── Sportswear — Men ─────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['sportswear-men'],
      name:           'HAXEL Performance Tee',
      slug:           'haxel-performance-tee',
      description:    'Lightweight performance tee in sage green with moisture-wicking fabric and raglan sleeves. Features the iconic HAXEL "X" logo on the chest and three-stripe detail on the sleeve. Built for training, made for the streets.',
      price:          699,
      stock_qty:      50,
      is_new_arrival: true,
      image_url:      '/uploads/sport_upload_01.png',
      image_gallery:  j(['/uploads/sport_upload_01.png']),
      colors:         j(['Green']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Green: '/uploads/sport_upload_01.png' }),
    },
    {
      category_id:    cat['sportswear-men'],
      name:           'HAXEL Quarter-Zip Long Sleeve',
      slug:           'haxel-quarter-zip-long-sleeve',
      description:    'Technical long-sleeve quarter-zip top in deep teal performance fabric. Features the HAXEL "X" logo on the chest, raglan sleeves, and a smooth moisture-wicking finish. Perfect for training sessions and post-workout styling.',
      price:          999,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/sport_upload_04.jpg',
      image_gallery:  j(['/uploads/sport_upload_04.jpg']),
      colors:         j(['Blue']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Blue: '/uploads/sport_upload_04.jpg' }),
    },
    {
      category_id:    cat['sportswear-men'],
      name:           'HAXEL Woven Jogger Pants',
      slug:           'haxel-woven-jogger-pants',
      description:    'Relaxed-fit woven joggers in khaki beige with an elasticated drawstring waist and ribbed cuffs. Features the HAXEL logo on the thigh and a zip side pocket. Lightweight, breathable, and built for performance and everyday wear.',
      price:          899,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/sport_upload_02.jpg',
      image_gallery:  j(['/uploads/sport_upload_02.jpg']),
      colors:         j(['Khaki']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Khaki: '/uploads/sport_upload_02.jpg' }),
    },
    {
      category_id:    cat['sportswear-men'],
      name:           'HAXEL Track Pants',
      slug:           'haxel-track-pants',
      description:    'Slim-fit track pants in matte black with a bold white stripe running down the leg. Features the HAXEL "X" logo at the hip, side slash pockets, and a tapered silhouette. A clean athletic staple that goes from gym to street.',
      price:          949,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/sport_upload_03.png',
      image_gallery:  j(['/uploads/sport_upload_03.png']),
      colors:         j(['Black']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Black: '/uploads/sport_upload_03.png' }),
    },
    {
      category_id:    cat['sportswear-men'],
      name:           'HAXEL Grey Quarter-Zip Long Sleeve',
      slug:           'haxel-grey-quarter-zip-long-sleeve',
      description:    'Technical quarter-zip long-sleeve top in slate grey performance fabric. Features the HAXEL "X" logo on the chest and smooth moisture-wicking finish. Pairs perfectly with any HAXEL bottom — from the gym to the street.',
      price:          999,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/sport2_upload_00.jpg',
      image_gallery:  j(['/uploads/sport2_upload_00.jpg']),
      colors:         j(['Gray']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Gray: '/uploads/sport2_upload_00.jpg' }),
    },
    {
      category_id:    cat['sportswear-men'],
      name:           'HAXEL Avocado Graphic Tee',
      slug:           'haxel-avocado-graphic-tee',
      description:    'Oversized heavyweight tee in crisp white featuring the HAXEL signature avocado character graphic — lifting dumbbells and ready to grind. With the HAXEL "X" logo on the chest. 100% premium cotton, drop-shoulder boxy fit. Because even your tee should hit the gym.',
      price:          749,
      stock_qty:      45,
      is_new_arrival: true,
      image_url:      '/uploads/sport2_upload_01.jpg',
      image_gallery:  j(['/uploads/sport2_upload_01.jpg']),
      colors:         j(['White']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ White: '/uploads/sport2_upload_01.jpg' }),
    },
    {
      category_id:    cat['sportswear-men'],
      name:           'HAXEL Training Shorts',
      slug:           'haxel-training-shorts',
      description:    'Lightweight woven training shorts in matte black. Features an elasticated waist, side pockets, and the HAXEL logo at the hem. Built for performance — fast-drying, breathable, and clean enough to wear beyond the gym.',
      price:          649,
      stock_qty:      50,
      is_new_arrival: true,
      image_url:      '/uploads/sport2_upload_02.jpg',
      image_gallery:  j(['/uploads/sport2_upload_02.jpg']),
      colors:         j(['Black']),
      sizes:          j(['S', 'M', 'L', 'XL', 'XXL']),
      color_images:   j({ Black: '/uploads/sport2_upload_02.jpg' }),
    },
  ]);

  // ── Sportswear — Women ───────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['sportswear-women'],
      name:           'HAXEL Women Fitted Zip-Up Training Jacket — Brown',
      slug:           'haxel-women-fitted-zip-up-training-jacket-brown',
      description:    'Sleek fitted zip-up training jacket in rich chocolate brown. Features a mock-neck collar, full-length zip closure, and four-way stretch performance fabric that moves with you. Raglan sleeves and contoured seams create a flattering silhouette whether you\'re lifting, cycling, or cooling down.',
      price:          999,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/wsport_upload_00.jpg',
      image_gallery:  j(['/uploads/wsport_upload_00.jpg']),
      colors:         j(['Brown']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Brown: '/uploads/wsport_upload_00.jpg' }),
    },
    {
      category_id:    cat['sportswear-women'],
      name:           'HAXEL Women Slim Full-Zip Performance Top — Black',
      slug:           'haxel-women-slim-full-zip-performance-top-black',
      description:    'Minimalist full-zip performance top in jet black. Lightweight, body-skimming fit with a smooth matte finish that pairs effortlessly with any training bottoms. Moisture-wicking fabric keeps you dry through every rep — perfect for layering or wearing solo.',
      price:          899,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/wsport_upload_01.jpg',
      image_gallery:  j(['/uploads/wsport_upload_01.jpg']),
      colors:         j(['Black']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Black: '/uploads/wsport_upload_01.jpg' }),
    },
    {
      category_id:    cat['sportswear-women'],
      name:           'HAXEL Women Quarter-Zip Running Top — Navy',
      slug:           'haxel-women-quarter-zip-running-top-navy',
      description:    'HAXEL signature quarter-zip long-sleeve top in deep navy. Features the iconic X logo on the chest and a curved hem for extra coverage during movement. Four-way stretch, quick-dry fabric makes this the ideal training layer for runs, gym sessions, or outdoor workouts.',
      price:          849,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/wsport_upload_02.jpg',
      image_gallery:  j(['/uploads/wsport_upload_02.jpg']),
      colors:         j(['Navy']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Navy: '/uploads/wsport_upload_02.jpg' }),
    },
    {
      category_id:    cat['sportswear-women'],
      name:           'HAXEL Women Seamless High-Waist Leggings — Black',
      slug:           'haxel-women-seamless-high-waist-leggings-black',
      description:    'HAXEL seamless high-waist leggings in classic black. Wide compression waistband and sculpting seamless construction hug every curve without restriction. Features the signature X logo on the thigh. Moisture-wicking, squat-proof fabric — your go-to for everything from yoga to HIIT.',
      price:          749,
      stock_qty:      45,
      is_new_arrival: true,
      image_url:      '/uploads/wsport_upload_03.jpg',
      image_gallery:  j(['/uploads/wsport_upload_03.jpg']),
      colors:         j(['Black']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Black: '/uploads/wsport_upload_03.jpg' }),
    },
    {
      category_id:    cat['sportswear-women'],
      name:           'HAXEL Women Quarter-Zip Running Top — White',
      slug:           'haxel-women-quarter-zip-running-top-white',
      description:    'Clean and bright HAXEL quarter-zip top in crisp white. Soft-touch performance fabric with the iconic X logo at the chest. The relaxed mock-neck and quarter-zip placket let you fine-tune ventilation on the go. A versatile training essential that transitions from warm-up to cool-down.',
      price:          849,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/wsport_upload_04.jpg',
      image_gallery:  j(['/uploads/wsport_upload_04.jpg']),
      colors:         j(['White']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ White: '/uploads/wsport_upload_04.jpg' }),
    },
    {
      category_id:    cat['sportswear-women'],
      name:           'HAXEL Women Quarter-Zip Training Top — Black/White',
      slug:           'haxel-women-quarter-zip-training-top-black-white',
      description:    'Performance quarter-zip training top in black with contrast white side panels. Features the iconic HAXEL X logo at the chest and a mock-neck zip collar for adjustable ventilation. Four-way stretch, moisture-wicking fabric keeps you cool and unrestricted through every workout. A bold yet clean essential for the serious athlete.',
      price:          849,
      stock_qty:      33,
      is_new_arrival: true,
      image_url:      '/uploads/wsport2_upload_00.png',
      image_gallery:  j(['/uploads/wsport2_upload_00.png']),
      colors:         j(['Black']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Black: '/uploads/wsport2_upload_00.png' }),
    },
    {
      category_id:    cat['sportswear-women'],
      name:           'HAXEL Women High-Waist Leggings — Cobalt Blue',
      slug:           'haxel-women-high-waist-leggings-cobalt-blue',
      description:    'Vibrant cobalt blue high-waist leggings with the signature HAXEL X logo on the thigh. Sculpting compression waistband and seamless-feel construction hug your curves without restriction. Squat-proof, moisture-wicking fabric with a smooth second-skin finish — built for performance, styled for everything else.',
      price:          749,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/wsport2_upload_01.png',
      image_gallery:  j(['/uploads/wsport2_upload_01.png']),
      colors:         j(['Blue']),
      sizes:          j(['XS', 'S', 'M', 'L', 'XL']),
      color_images:   j({ Blue: '/uploads/wsport2_upload_01.png' }),
    },
  ]);

  // ── Accessories ──────────────────────────────────────────────────────────────
  await knex('products').insert([
    {
      category_id:    cat['accessories'],
      name:           'Pleated Hand Fan — Rose Pink',
      slug:           'pleated-hand-fan-rose-pink',
      description:    'Elegant pleated hand fan in soft rose pink with a deep burgundy resin handle. Folds compact for easy carry and opens to a full semi-circle. A chic summer essential that adds instant flair to any outfit — whether at an outdoor event, rooftop, or beach.',
      price:          299,
      stock_qty:      50,
      is_new_arrival: true,
      image_url:      '/uploads/acc_upload_00.png',
      image_gallery:  j(['/uploads/acc_upload_00.png']),
      colors:         j(['Rose']),
      sizes:          j(['One Size']),
      color_images:   j({ Rose: '/uploads/acc_upload_00.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Classic Baseball Cap — Forest Green',
      slug:           'classic-baseball-cap-forest-green',
      description:    'Structured six-panel baseball cap in rich forest green. Premium cotton twill with a pre-curved brim and adjustable back strap for the perfect fit. Clean, logo-free design that pairs effortlessly with casual or sportswear looks.',
      price:          449,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/acc_upload_01.png',
      image_gallery:  j(['/uploads/acc_upload_01.png']),
      colors:         j(['Green']),
      sizes:          j(['One Size']),
      color_images:   j({ Green: '/uploads/acc_upload_01.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Sport Diver Watch — Navy Blue',
      slug:           'sport-diver-watch-navy-blue',
      description:    'Bold sport-style diver watch with a textured navy blue silicone strap and gunmetal-tone case. The embossed dial features luminous yellow-green indices and a crocodile logo at 12 o\'clock. Water-resistant build and screwdown crown make it as tough as it looks.',
      price:          2499,
      stock_qty:      20,
      is_new_arrival: true,
      image_url:      '/uploads/acc_upload_02.png',
      image_gallery:  j(['/uploads/acc_upload_02.png']),
      colors:         j(['Navy']),
      sizes:          j(['One Size']),
      color_images:   j({ Navy: '/uploads/acc_upload_02.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Chronograph Sport Watch — Steel Blue',
      slug:           'chronograph-sport-watch-steel-blue',
      description:    'Sleek chronograph watch with a steel-blue silicone mesh strap and navy aluminium case. Multi-function dial with sub-dials for precise timekeeping. Crocodile logo at 12 o\'clock and water-resistant casing — the ideal blend of technical performance and understated style.',
      price:          2999,
      stock_qty:      20,
      is_new_arrival: true,
      image_url:      '/uploads/acc_upload_03.png',
      image_gallery:  j(['/uploads/acc_upload_03.png']),
      colors:         j(['Blue']),
      sizes:          j(['One Size']),
      color_images:   j({ Blue: '/uploads/acc_upload_03.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Multifunction Watch — White & Rose Gold',
      slug:           'multifunction-watch-white-rose-gold',
      description:    'Elegant multifunction watch with a clean white silicone strap and rose gold-tone case. The off-white multi-eye dial features a crocodile logo and three functional sub-dials. Feminine yet refined — a versatile timepiece that elevates both casual and dressed-up looks.',
      price:          2799,
      stock_qty:      20,
      is_new_arrival: true,
      image_url:      '/uploads/acc_upload_04.png',
      image_gallery:  j(['/uploads/acc_upload_04.png']),
      colors:         j(['White']),
      sizes:          j(['One Size']),
      color_images:   j({ White: '/uploads/acc_upload_04.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Sport Baseball Cap — Navy',
      slug:           'sport-baseball-cap-navy',
      description:    'Lightweight sport baseball cap in classic navy with an adjustable slide-back strap and embroidered crocodile logo. Water-repellent microfibre shell with a curved brim and structured six-panel crown. A clean, athletic essential for any outdoor occasion.',
      price:          449,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/acc2_upload_00.png',
      image_gallery:  j(['/uploads/acc2_upload_00.png']),
      colors:         j(['Navy']),
      sizes:          j(['One Size']),
      color_images:   j({ Navy: '/uploads/acc2_upload_00.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Square Frame Glasses — Black',
      slug:           'square-frame-glasses-black',
      description:    'Sleek oversized square-frame glasses with a glossy black acetate frame and light tinted lenses. Retro-inspired silhouette that adds instant edge to any look. UV-protective lenses and spring-hinge temples for all-day comfort.',
      price:          349,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/acc2_upload_01.png',
      image_gallery:  j(['/uploads/acc2_upload_01.png']),
      colors:         j(['Black']),
      sizes:          j(['One Size']),
      color_images:   j({ Black: '/uploads/acc2_upload_01.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Crochet Tassel Scarf — Black',
      slug:           'crochet-tassel-scarf-black',
      description:    'Handcrafted crochet scarf in all-black with an intricate floral openwork pattern and a fringe of layered tassels along the hem. Versatile enough to wear as a scarf, shawl, or head wrap — a bohemian statement piece with artisan detail.',
      price:          399,
      stock_qty:      25,
      is_new_arrival: true,
      image_url:      '/uploads/acc2_upload_02_v2.jpg',
      image_gallery:  j(['/uploads/acc2_upload_02_v2.jpg']),
      colors:         j(['Black']),
      sizes:          j(['One Size']),
      color_images:   j({ Black: '/uploads/acc2_upload_02_v2.jpg' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Layered Beaded Necklace — Amber',
      slug:           'layered-beaded-necklace-amber',
      description:    'Luxurious multi-strand layered necklace featuring mixed amber, caramel, and translucent brown beads in varying sizes. Five cascading strands create a rich, statement-making drape. Finished with a gold-tone extender chain for an adjustable fit.',
      price:          499,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/acc2_upload_03.png',
      image_gallery:  j(['/uploads/acc2_upload_03.png']),
      colors:         j(['Brown']),
      sizes:          j(['One Size']),
      color_images:   j({ Brown: '/uploads/acc2_upload_03.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Leather Bucket Bag — Black',
      slug:           'leather-bucket-bag-black',
      description:    'Structured mini bucket bag in smooth black vegan leather with a beige satin drawstring interior. Features a short top handle and an adjustable crossbody strap with gold-tone hardware. Angular silhouette with contrast stitching detail — a refined everyday carry that works from day to night.',
      price:          1299,
      stock_qty:      20,
      is_new_arrival: true,
      image_url:      '/uploads/acc2_upload_04.png',
      image_gallery:  j(['/uploads/acc2_upload_04.png']),
      colors:         j(['Black']),
      sizes:          j(['One Size']),
      color_images:   j({ Black: '/uploads/acc2_upload_04.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Tortoiseshell Claw Hair Clip',
      slug:           'tortoiseshell-claw-hair-clip',
      description:    'Oversized sculptural claw clip in rich tortoiseshell acetate with a bold swirling wave design. Gold-tone spring mechanism for a secure hold on all hair types. A statement hair accessory that adds instant polished flair to any look — half-up, full updo, or effortless twist.',
      price:          199,
      stock_qty:      50,
      is_new_arrival: true,
      image_url:      '/uploads/acc3_upload_00.png',
      image_gallery:  j(['/uploads/acc3_upload_00.png']),
      colors:         j(['Brown']),
      sizes:          j(['One Size']),
      color_images:   j({ Brown: '/uploads/acc3_upload_00.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Suede Baseball Cap — Brown',
      slug:           'suede-baseball-cap-brown',
      description:    'Unstructured six-panel cap in soft brown suede with a tonal button crown and adjustable blue rope drawstring closure. Low-profile, lived-in silhouette with an artisan feel. A unique streetwear-meets-outdoor piece that pairs equally well with joggers or denim.',
      price:          599,
      stock_qty:      30,
      is_new_arrival: true,
      image_url:      '/uploads/acc3_upload_01.png',
      image_gallery:  j(['/uploads/acc3_upload_01.png']),
      colors:         j(['Brown']),
      sizes:          j(['One Size']),
      color_images:   j({ Brown: '/uploads/acc3_upload_01.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Layered Chain Necklace with Teardrop Pendant — Gold',
      slug:           'layered-chain-necklace-teardrop-pendant-gold',
      description:    'Delicate double-layer gold-tone necklace featuring a fine curb chain and an open-link cable chain, finished with a polished teardrop pendant. Lobster-claw clasp with an extender chain for adjustable length. Effortlessly minimal — pairs seamlessly with any neckline.',
      price:          299,
      stock_qty:      40,
      is_new_arrival: true,
      image_url:      '/uploads/acc3_upload_02.png',
      image_gallery:  j(['/uploads/acc3_upload_02.png']),
      colors:         j(['Camel']),
      sizes:          j(['One Size']),
      color_images:   j({ Camel: '/uploads/acc3_upload_02.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Gold Cuff Bracelet Set',
      slug:           'gold-cuff-bracelet-set',
      description:    'Set of two open-ended cuff bracelets in warm gold-tone metal — one sleek and polished, one with a faceted diamond-cut texture. Flexible C-shape for an adjustable fit on most wrists. Stack them together or wear individually for a versatile everyday jewellery essential.',
      price:          349,
      stock_qty:      35,
      is_new_arrival: true,
      image_url:      '/uploads/acc3_upload_03.png',
      image_gallery:  j(['/uploads/acc3_upload_03.png']),
      colors:         j(['Camel']),
      sizes:          j(['One Size']),
      color_images:   j({ Camel: '/uploads/acc3_upload_03.png' }),
    },
    {
      category_id:    cat['accessories'],
      name:           'Woven Raffia Hobo Bag — Natural',
      slug:           'woven-raffia-hobo-bag-natural',
      description:    'Crescent-shaped hobo bag handwoven in natural raffia straw with an open-weave texture and a knotted toggle closure at the front. Finished with a nude leather shoulder strap and gold-tone hardware. A lightweight summer essential that transitions from beach to brunch with ease.',
      price:          899,
      stock_qty:      25,
      is_new_arrival: true,
      image_url:      '/uploads/acc3_upload_04.jpg',
      image_gallery:  j(['/uploads/acc3_upload_04.jpg']),
      colors:         j(['Beige']),
      sizes:          j(['One Size']),
      color_images:   j({ Beige: '/uploads/acc3_upload_04.jpg' }),
    },
  ]);

  console.log('Seed completed successfully — all products inserted.');
}
